#sudo: false
#dist: xenial
#language: python
#python:
#  - "2.7"
#  - "3.4"
#  - "3.5"
#  - "3.6"
#  - "3.7"
#  - "3.8"
#matrix:
#  include:
#    - python: 2.6
#      dist: trusty
#install:
#  - travis_retry pip install tox-travis
#script:
#  - tox
